title: o0w0b の homepage
description: o0w0b の homepage
favicon: "/img/favicon144.jpg"
author: o0w0b
keywords: "o0w0b, homepage"
ICP: ""
manifest:
  name: o0w0b の homepage # 全称
  short_name: o0w0b の homepage # 简称
  description: o0w0b の homepage
  theme_color: "#128AFA"
  start_url: /
  id: Homepage
  icons:
    - src: /img/favicon512.jpg
      sizes: 512x512
      purpose: any maskable
    - src: /img/favicon144.jpg
      sizes: 144x144
level: 1
exp: 11
nextExp: 26
iconfont: "https://at.alicdn.com/t/c/font_5082259_rwfef5xw7q.css"
dock:
  - name: jsDelivr
    href: "https://www.jsdelivr.com/github"
    imgSrc: /icon/jsdelivr_Icon.ico
  - name: Netdisk
    href: "https://netdisk.o0w0b.top"
    imgSrc: /icon/Netdisk_Icon.png
  - name: ImgBed
    href: "https://imgbed.o0w0b.top"
    imgSrc: /icon/ImgBed_Icon.png
contact:
  - name: gitee
    href: "https://gitee.com"
    iconfont: icon-gitee
  - name: Github
    href: "https://github.com"
    iconfont: icon-github
  - name: npmjs
    href: "https://npmjs.com"
    iconfont: icon-npmjs
  - name: Vercel
    href: "https://vercel.com"
    iconfont: icon-vercel
  - name: ClawCloud
    href: "https://ap-northeast-1.run.claw.cloud"
    imgSrc: /icon/clawcloud_Icon.ico
  - name: Cloudflare
    href: "https://dash.cloudflare.com"
    iconfont: icon-cloudflare
task:
  name: Blog
  href: "https://blog.o0w0b.top"
banner:
  enable: # 是否添加音乐播放器
    false
  musicID: # 音乐ID（暂时只支持网易云音乐）
    - 2098478355

memorialLobbies:
  # - name: # 这里填学生名字
  #   path: # 这里填回忆大厅L2D文件位置（注意最后以“/”结尾）
  #   skel: # 这里填回忆大厅L2D的SKEL文件
  #   atlas: # 这里填回忆大厅L2D的ATLAS文件
  #   voice: # 这里填学生对话（注意：前面的必须是L2D文件中有的内容，实在不清楚的可以在调试的时候获取"Background.vue"文件"onEvent"函数的"event.stringValue"的值以确保无误）
  #   offset: # 这里填学生在回忆大厅的位置，方便在小屏时居中定位学生（百分比定位）
  #   dialogueDisplay: # 这里填学生对话框位置（百分比定位）
  #     x:
  #     y:
  #     position: # 这里是对话框朝向（left/right）
  - name: Yuuka
    path: "/l2d/Yuuka/"
    skel: "CH0284_home.skel"
    atlas: "CH0284_home.atlas"
    bgm: "https://cdn.jsdelivr.net/gh/o0w0b/StaticFiles@main/music/Theme_216.ogg"
    voice:
      CH0284_MemorialLobby_0_1: ლ(´ڡ`ლ)
      CH0284_MemorialLobby_0_2: w(ﾟДﾟ)w
      CH0284_MemorialLobby_1: せ、先生？こんな時間にどうして……？
      CH0284_MemorialLobby_2_1: え、えっと……これは、その……
      CH0284_MemorialLobby_2_2: ちょっと寝付けなくて、散歩に出たら……
      CH0284_MemorialLobby_2_3: そこの貼り紙の「エンジェルチキン」が目に入ったんです……。
      CH0284_MemorialLobby_3_1: だ、だって、仕方ないでしょう？
      CH0284_MemorialLobby_3_2: この時間のエンジェルチキンは、揚げたてなんです！
      CH0284_MemorialLobby_3_3: あっつあつで肉汁たっぷりなんですから！買わない手はありません！
      CH0284_MemorialLobby_4_1: だ、だからその……別に、毎日毎日、
      CH0284_MemorialLobby_4_2: 夜食を取ってるわけじゃ、ないんですから……。
      CH0284_MemorialLobby_5_1: えっと……よかったら、
      CH0284_MemorialLobby_5_2: 先生も一口、食べますか？
    offset: 0.61
    dialogueDisplay:
      x: 1/8 + 1/8
      y: 1/8
      position: left
  - name: Shiroko
    path: "/l2d/Shiroko/"
    skel: "LobbyShiroko_multi.skel"
    atlas: "LobbyShiroko_multi.atlas"
    bgm: "https://cdn.jsdelivr.net/gh/o0w0b/StaticFiles@main/music/BlueNewWorld_Lobby.ogg"
    voice:
    offset: 0.32
    dialogueDisplay:
      x:
      y:
      position:
  - name: Hoshino
    path: "/l2d/Hoshino/"
    skel: "LobbyHoshino_multi.skel"
    atlas: "LobbyHoshino_multi.atlas"
    bgm: "https://cdn.jsdelivr.net/gh/o0w0b/StaticFiles@main/music/Theme_234.ogg"
    voice:
    offset: 0.32
    dialogueDisplay:
      x:
      y:
      position:
  - name: Nonomi
    path: "/l2d/Nonomi/"
    skel: "LobbyNonomi_multi.skel"
    atlas: "LobbyNonomi_multi.atlas"
    bgm: "https://cdn.jsdelivr.net/gh/o0w0b/StaticFiles@main/music/Theme_228.ogg"
    voice:
    offset: 0.30
    dialogueDisplay:
      x:
      y:
      position:
  - name: Serika
    path: "/l2d/Serika/"
    skel: "LobbySerika_multi.skel"
    atlas: "LobbySerika_multi.atlas"
    bgm: "https://cdn.jsdelivr.net/gh/o0w0b/StaticFiles@main/music/Mitsukiyo - Dive into Summer.mp3"
    voice:
    offset: 0.72
    dialogueDisplay:
      x:
      y:
      position:
  - name: Ayane
    path: "/l2d/Ayane/"
    skel: "LobbyAyane_multi.skel"
    atlas: "LobbyAyane_multi.atlas"
    bgm: "https://cdn.jsdelivr.net/gh/o0w0b/StaticFiles@main/music/Theme_222.ogg"
    voice:
    offset: 0.68
    dialogueDisplay:
      x:
      y:
      position:
translate:
  about: 关于
  projectWebsite: 项目地址：
  info: 通知
  ifSkip: 是否跳过？
  update: 站点已更新，刷新即可访问最新内容！
  ok: 确认
  cancel: 取消
